Ссылка на колаб Берт
Попытка запустить классификацию фраз на русскоязычном Берте. Пока неудачно
Ошибка совместимости с GPU
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.